### ISSUE TITLE
Numbers of files created and revised

### ISSUE THREAD

**Issue by ontrou** [trydalch/obsidian-daily-activity#1]
Thank you Trevor for your plugin. It works great just as is. I am wondering if it is possible to add how many files were changed or created. E.g., 2 notes created; 7 notes revised. My use for your plugin is to monitor how productive I am, and whether I meet the targets I set for myself. The # of files create is a proxy for writing productiviy, and # revisions for new connected I create between notes. Thanks for sharing this with the Obsidian community.

**Comment by trydalch** [comment]
@ontrou That's a great idea. This plugin is in it's infancy, and there's a lot of things that I'd like to do going forward. If this could help you, I'll bump it up my list. 

It would not be too difficult. I'll add it as an additional command.

**Comment by trydalch** [comment]
@ontrou take a look and let me know what you think.

**Comment by ontrou** [comment]
This is great. Thank you. A very useful plugin.
