### ISSUE TITLE
There is not Links to Files Modified Today command

### ISSUE THREAD

**Issue by fatFire** [trydalch/obsidian-daily-activity#11]
![image](https://user-images.githubusercontent.com/33923314/114681946-36a2b500-9d41-11eb-88c9-85817da41ff5.png)

I hava installed this plugin again, but there is not Links to Files Modified Today command.

**Comment by fatFire** [comment]
![image](https://user-images.githubusercontent.com/33923314/114682479-b4ff5700-9d41-11eb-90ed-c8b3d1c35b75.png)

**Comment by trydalch** [comment]
Will take a look.
