### ISSUE TITLE
Command "Links to Files MODIFIED today" not found

### ISSUE THREAD

**Issue by OXiOSDev** [trydalch/obsidian-daily-activity#14]
Hi,
First of all, thank you for this Obsidian's plugin.
I don't find the command "Links to files Modified today" in the Command Pallet.
Could you confirm me that this command doesn't exist; or do I a mistake ?

Thank you for you help

**Comment by pdxrlk** [comment]
+1 same here...

**Comment by pdxrlk** [comment]
Line 5210 in main.js has the error.  It should read:
`
        id: 'files-modified-today',
`
