### ISSUE TITLE
File lists for dates other than today

### ISSUE THREAD

**Issue by oldjove** [trydalch/obsidian-daily-activity#17]
Would it be possible to add an option to generate a list of files created/modified on dates other than today? E.g. I'd like to be able to go to a past daily note and generate a list of files created/modified on that day.

Thanks!

**Comment by mvandermeulen** [comment]
I also have been trying to find a way to achieve this for quite a while now. Is development on this plugin still active? I don't want to get my hopes up if it's no longer maintained.

I'm very thankful to the author for giving us such a great plugin though. Cheers fella

**Comment by trydalch** [comment]
I haven't touched this plugin for quite a while, but I'm taking a look now 😄 shouldn't be too difficult to add this, I would think.

**Comment by trydalch** [comment]
Version 0.4.0 now supports this. Type the date (or date range) you want the list of files for, select it, and then run one of the commands. If no date or date range is selected, it defaults to today's list.
