### ISSUE TITLE
Auto-Propagate Daily Note

### ISSUE THREAD

**Issue by aidan-gibson** [trydalch/obsidian-daily-activity#18]
First off, thank you for this extremely useful plug-in!

Do you have any recommended workflows to automatically add modified file links to my daily note? Ideally, it would add the links as I go throughout my day, but it might be easier to automate it for every previous day instead of constantly adding more files as I go.

Again, thank you for this!

**Comment by aidan-gibson** [comment]
Also if the daily note wasn't created but files were modified that day, this automation should generate the daily.

Totally realize this might be out of scope for what you had in mind for this plugin, but definitely appreciate any advice!

**Comment by papatistos** [comment]
@aidan-gibson did you find a way to automate this?

**Comment by aidan-gibson** [comment]
Found someone who did! https://github.com/franciskafieh/obsidian-list-modified
Works beautifully.
