### ISSUE TITLE
Allow Unlinked

### ISSUE THREAD

**Issue by TheTuxCrusader** [trydalch/obsidian-daily-activity#6]
Allow an option to insert data without the links.

**Comment by trydalch** [comment]
So just the list of file names?

**Comment by TheTuxCrusader** [comment]
> So just the list of file names?

Yea, I wouldn't mind having a log like page that can show what files have been changed etc. But may not necessarily want all the files linking to that as it not necessarily relevant to those file.

Does that make sense? I'd still have it as it currently is but just have the options either way so the user can chose depend on their use.

**Comment by trydalch** [comment]
Do you think this would be better as a setting or as an additional command?

**Comment by trydalch** [comment]
Added 2 new commands to insert lists in plain text rather than links. update to version 0.3.1

**Comment by TheTuxCrusader** [comment]
> Added 2 new commands to insert lists in plain text rather than links. update to version 0.3.1

Just happened to see this earlier today. Thanks.
