### ISSUE TITLE
Retrieve date from the file's title date referential

### ISSUE THREAD

**Issue by ontrou** [trydalch/obsidian-daily-activity#7]
Is it possible to retrieve the daily activity from a day other than the current date?

My use case: I create a daily note in the morning. At the end of the workday, I try to remember to invoke the the Daily Activity command. But sometimes I forget, and I would like to be able to retrieve them the next day. So either "today's day offset -1" or just any date based on the file's title date referential.

Thank you trydalch. A real treat to be able to have today's stats (when I remember to invoke them!)

**Comment by trydalch** [comment]
This is something I've wanted as well, I've just been mulling over how to allow users to select the date.

If we limit it to a single date, there's a few ways we can do that. 

1. Extract it from the file's title (as long as it's in moment format, but how to deal with extra text?)
2. Require typing the date, selecting it in the editor prior to running the command (easiest)
3. Provide a dropdown suggestion modal (same UI as the command's dropdown) that gives a list of dates all the way back to the date of the oldest file in the vault

What do you think?

**Comment by trydalch** [comment]
Option 2 could also allow for specifying a date range.

**Comment by ontrou** [comment]
I say option 2. It is not a burden to type the date, and date ranges is a great enhancement.

**Comment by tallguyjenks** [comment]
what about also utilizing the NLP Dates plugin for natural language for date grabbing? "Last tuesday" or "18 days ago"

**Comment by trydalch** [comment]
@tallguyjenks is there a way to leverage other plugins or are they sandboxed? 

That would be nice to have, but would also introduce a dependency that others might not have.

**Comment by tallguyjenks** [comment]
@trydalch It's what ryan Murphy did for the review plugin so I know you CAN do it

**Comment by trydalch** [comment]
Cool. I'm new to Obsidian, so I appreciate all the ideas. I'll take a look.

**Comment by ontrou** [comment]
I don't know why I have an opinion on this since I don't write programs, but SilentVoid13's [Templater](https://github.com/SilentVoid13/Templaterl) plugin may be of use to you too. It exposes all kinds of date options with laser-like precision.
